#
# PX4 v1.11.2 SITL testing environment for MAVSDK based on Ubuntu 20.04.
# Author: Julian Oes <julian@oes.ch>
#
FROM mavsdk/mavsdk-ubuntu-20.04
MAINTAINER Yogesh Khedar <yogeshkhedar@gmail.com>

ENV FIRMWARE_DIR ${WORKDIR}../ArduPilot

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get --quiet -y --no-install-recommends install git locales python-is-python3 libpython3-stdlib \
                                libxml2-dev libxml2-utils libxslt-dev python3 python3-pip python3-dev python3-setuptools python3-wheel \
                                gnupg g++ gcc gdb lcov rsync shellcheck psmisc \
                                && apt-get -y autoremove \
                                && apt-get clean autoclean \
                                && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN git clone https://github.com/ArduPilot/ardupilot.git ${FIRMWARE_DIR}
ENV COPTER_VERSION=Copter-4.1.2
RUN git -C ${FIRMWARE_DIR} checkout ${COPTER_VERSION}
RUN git -C ${FIRMWARE_DIR} submodule update --init --recursive

RUN cd ${FIRMWARE_DIR} && sed -i 's/sudo //' Tools/environment_install/install-prereqs-ubuntu.sh && \
    sed -i '6,9d' Tools/environment_install/install-prereqs-ubuntu.sh && \
    sed -i '/usermod -a -G dialout/d' Tools/environment_install/install-prereqs-ubuntu.sh && \
    bash Tools/environment_install/install-prereqs-ubuntu.sh -y

RUN cd ${FIRMWARE_DIR} && ./waf distclean && ./waf configure --board sitl && ./waf copter

RUN echo "export PATH=$PATH:/root/.local/bin" >> ~/.bashrc

ENV APM_VEHICLE ArduCopter 
ENV APM_HOME_LAT 47.397742
ENV APM_HOME_LONG 8.545594
ENV APM_HOME_ALT 488.0
ENV APM_HOME_DIR 180
ENV APM_FRAME quad
ENV WORKDIR "/home/user/MAVSDK"
ENV FIRMWARE_DIR ${WORKDIR}/../ArduPilot
ENV PYTHONPATH "${PYTHONPATH}:/root/.local/lib/python3.8/site-packages:/home/user/ArduPilot"
ENV PATH=$PATH:/root/.local/bin

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get --quiet -y --no-install-recommends install screen && apt-get -y autoremove \
                                && apt-get clean autoclean \
                                && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*






